version: '3'
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - nginx-gen
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    environment:
      ENABLE_IPV6: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      RESOLVERS: "1.1.1.1"

  nginx-letsencrypt:
   image: jrcs/letsencrypt-nginx-proxy-companion
   container_name: nginx-letsencrypt
   restart: always
   depends_on:
     - nginx-proxy
     - nginx-gen
   volumes:
     - ./conf.d:/etc/nginx/conf.d
     - ./vhost.d:/etc/nginx/vhost.d
     - ./html:/usr/share/nginx/html
     - ./certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
   environment:
     NGINX_PROXY_CONTAINER: "nginx-proxy"
     NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
     # Debug/staging:
     #ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
     #DEBUG: "true"
   logging:
     driver: "json-file"
     options:
       max-size: "1m"
       max-file: "3"
    
volumes:
  certs:
  conf.d:
  html:
  htpasswd:
  vhost.d:
    
networks:
  default:
    external:
      name: nginx-proxy
